#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$REPO_ROOT/build/adapters"
SYNC_SNAPSHOTS=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)
            [[ $# -ge 2 ]] || { echo "--output-dir needs a value" >&2; exit 2; }
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --sync-snapshots)
            SYNC_SNAPSHOTS=true
            shift
            ;;
        -h|--help)
            echo "Usage: bash scripts/build-adapters.sh [--output-dir DIR] [--sync-snapshots]"
            exit 0
            ;;
        *)
            echo "Unknown parameter: $1" >&2
            exit 2
            ;;
    esac
done

mkdir -p "$OUTPUT_DIR"

read_normalized() {
    awk 'BEGIN { count=0 } { lines[++count]=$0 } END { first=1; while (first <= count && lines[first] == "") first++; last=count; while (last >= first && lines[last] == "") last--; for (i=first; i<=last; i++) print lines[i] }' "$1"
}

frontmatter() {
    awk 'BEGIN { section=0 } /^---$/ { section++; if (section == 2) exit; next } section == 1 { print }' "$1"
}

body() {
    awk 'BEGIN { section=0; count=0 } /^---$/ { section++; next } section >= 2 { lines[++count]=$0 } END { first=1; while (first <= count && lines[first] == "") first++; last=count; while (last >= first && lines[last] == "") last--; for (i=first; i<=last; i++) print lines[i] }' "$1"
}

metadata() {
    local key="$1"
    local path="$2"
    frontmatter "$path" | sed -n -E "s/^${key}:[[:space:]]*//p" | head -n 1 | sed -E "s/^[\"']//; s/[\"']$//"
}

validate_name() {
    [[ "$1" =~ ^[a-z0-9][a-z0-9-]*$ ]] || {
        echo "Unsupported name '$1' in $2" >&2
        exit 1
    }
}

escape_toml_basic() {
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

render_rules() {
    local host="$1"
    local output_name="$2"
    local common="$REPO_ROOT/core/rules/common.md"
    local adapter="$REPO_ROOT/adapters/$host/rules.md"
    [[ -f "$common" && -f "$adapter" ]] || { echo "Missing rule source for adapter '$host'." >&2; exit 1; }
    mkdir -p "$OUTPUT_DIR/$host"
    {
        echo "<!-- Generated by scripts/build-adapters.sh. Edit core/rules or adapters instead. -->"
        if [[ "$host" == "antigravity" ]]; then
            printf '\n'
            cat <<'EOF'
---
name: global-rules
description: Global rules and constraints for all workspaces. Always active.
activation: always
---
EOF
        fi
        printf '\n'
        read_normalized "$common"
        printf '\n'
        read_normalized "$adapter"
    } > "$OUTPUT_DIR/$host/$output_name"
}

render_agent() {
    local path="$1"
    local name description agent_body
    name="$(metadata name "$path")"
    description="$(metadata description "$path")"
    validate_name "$name" "$path"
    [[ -n "$description" ]] || { echo "Missing description in $path" >&2; exit 1; }
    agent_body="$(body "$path")"
    [[ "$agent_body" != *"'''"* ]] || { echo "TOML delimiter found in $path" >&2; exit 1; }
    mkdir -p "$OUTPUT_DIR/codex/agents"
    {
        printf 'name = "%s"\n' "$(printf '%s' "$name" | escape_toml_basic)"
        printf 'description = "%s"\n' "$(printf '%s' "$description" | escape_toml_basic)"
        printf "developer_instructions = '''\n"
        printf '%s\n' "$agent_body"
        printf "'''\n"
    } > "$OUTPUT_DIR/codex/agents/$name.toml"
}

render_workflow_skill() {
    local path="$1"
    local name clean_front workflow_body
    name="$(metadata name "$path")"
    validate_name "$name" "$path"
    [[ ! -d "$REPO_ROOT/skills/$name" ]] || { echo "Workflow name '$name' collides with canonical skill directory: $path" >&2; exit 1; }
    clean_front="$(frontmatter "$path" | sed -E '/^[[:space:]]*(command|trigger):/d')"
    workflow_body="$(body "$path")"
    mkdir -p "$OUTPUT_DIR/workflow-skills/$name"
    {
        printf '%s\n' '---'
        printf '%s\n' "$clean_front"
        printf '%s\n\n' '---'
        printf '%s\n' "<!-- Generated workflow-to-skill bridge. Edit workflows/$(basename "$path") instead. -->"
        printf '%s\n\n' "> Host invocation: use the native workflow or skill selector for '$name'."
        printf '%s\n' "$workflow_body"
    } > "$OUTPUT_DIR/workflow-skills/$name/SKILL.md"
}

render_rules claude CLAUDE.md
render_rules antigravity GEMINI.md
render_rules codex AGENTS.md

for path in "$REPO_ROOT"/agents/*.md; do
    [[ -f "$path" ]] || continue
    render_agent "$path"
done

for path in "$REPO_ROOT"/workflows/*.md; do
    [[ -f "$path" ]] || continue
    render_workflow_skill "$path"
done

if [[ "$SYNC_SNAPSHOTS" == true ]]; then
    cp "$OUTPUT_DIR/claude/CLAUDE.md" "$REPO_ROOT/claude/CLAUDE.md"
    cp "$OUTPUT_DIR/antigravity/GEMINI.md" "$REPO_ROOT/gemini/GEMINI.md"
    echo "Synchronized claude/CLAUDE.md and gemini/GEMINI.md snapshots."
fi

agent_count="$(find "$OUTPUT_DIR/codex/agents" -maxdepth 1 -type f -name '*.toml' | wc -l | tr -d ' ')"
workflow_skill_count="$(find "$OUTPUT_DIR/workflow-skills" -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d ' ')"
echo "Built adapters: Codex agents=$agent_count, workflow skills=$workflow_skill_count"
