[CmdletBinding()]
param(
    [string]$OutputDir,
    [switch]$SyncSnapshots
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
if (-not $PSBoundParameters.ContainsKey("OutputDir")) {
    $OutputDir = Join-Path $RepoRoot "build\adapters"
}
$OutputDir = [System.IO.Path]::GetFullPath($OutputDir)

function Read-Normalized([string]$Path) {
    return (Get-Content -LiteralPath $Path -Raw).Replace("`r`n", "`n").Trim()
}

function Write-Utf8([string]$Path, [string]$Content) {
    $Parent = Split-Path -Parent $Path
    New-Item -ItemType Directory -Force -Path $Parent | Out-Null
    $Encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $Encoding)
}

function Read-MarkdownDocument([string]$Path) {
    $Text = Read-Normalized $Path
    $Match = [regex]::Match($Text, '(?s)\A---\n(.*?)\n---\n?(.*)\z')
    if (-not $Match.Success) {
        throw "Missing YAML frontmatter: $Path"
    }

    $FrontMatter = $Match.Groups[1].Value.Trim()
    $Body = $Match.Groups[2].Value.Trim()
    $NameMatch = [regex]::Match($FrontMatter, '(?m)^name:\s*(.+)$')
    $DescriptionMatch = [regex]::Match($FrontMatter, '(?m)^description:\s*(.+)$')
    if (-not $NameMatch.Success -or -not $DescriptionMatch.Success) {
        throw "Frontmatter must contain name and description: $Path"
    }

    $Name = $NameMatch.Groups[1].Value.Trim().Trim('"').Trim("'")
    $Description = $DescriptionMatch.Groups[1].Value.Trim().Trim('"').Trim("'")
    if ($Name -notmatch '^[a-z0-9][a-z0-9-]*$') {
        throw "Unsupported name '$Name' in $Path. Use lowercase letters, numbers, and hyphens."
    }

    return [pscustomobject]@{
        Name = $Name
        Description = $Description
        FrontMatter = $FrontMatter
        Body = $Body
    }
}

function Escape-TomlBasic([string]$Value) {
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

function Render-Rules([string]$HostName, [string]$OutputName) {
    $CommonPath = Join-Path $RepoRoot "core\rules\common.md"
    $AdapterPath = Join-Path $RepoRoot "adapters\$HostName\rules.md"
    if (-not (Test-Path -LiteralPath $CommonPath) -or -not (Test-Path -LiteralPath $AdapterPath)) {
        throw "Missing rule source for adapter '$HostName'."
    }

    $Parts = @(
        "<!-- Generated by scripts/build-adapters.ps1. Edit core/rules or adapters instead. -->"
    )
    if ($HostName -eq "antigravity") {
        $Parts += @(
            "---"
            "name: global-rules"
            "description: Global rules and constraints for all workspaces. Always active."
            "activation: always"
            "---"
        ) -join "`n"
    }
    $Parts += Read-Normalized $CommonPath
    $Parts += Read-Normalized $AdapterPath
    $Destination = Join-Path $OutputDir "$HostName\$OutputName"
    Write-Utf8 $Destination (($Parts -join "`n`n") + "`n")
}

function Render-CodexAgent([string]$Path) {
    $Document = Read-MarkdownDocument $Path
    if ($Document.Body.Contains("'''")) {
        throw "Agent body contains TOML multiline delimiter ''' and cannot be rendered safely: $Path"
    }

    $Toml = @(
        ('name = "' + (Escape-TomlBasic $Document.Name) + '"')
        ('description = "' + (Escape-TomlBasic $Document.Description) + '"')
        "developer_instructions = '''"
        $Document.Body
        "'''"
    ) -join "`n"
    $Destination = Join-Path $OutputDir "codex\agents\$($Document.Name).toml"
    Write-Utf8 $Destination ($Toml + "`n")
}

function Render-WorkflowSkill([string]$Path) {
    $Document = Read-MarkdownDocument $Path
    $CanonicalSkillPath = Join-Path $RepoRoot "skills\$($Document.Name)"
    if (Test-Path -LiteralPath $CanonicalSkillPath) {
        throw "Workflow name '$($Document.Name)' collides with canonical skill directory: $Path"
    }
    $CleanFrontMatter = ($Document.FrontMatter -split "`n" |
        Where-Object { $_ -notmatch '^\s*(command|trigger):' }) -join "`n"
    $Content = @(
        "---"
        $CleanFrontMatter.Trim()
        "---"
        ""
        "<!-- Generated workflow-to-skill bridge. Edit workflows/$([System.IO.Path]::GetFileName($Path)) instead. -->"
        "> Host invocation: use the native workflow or skill selector for '$($Document.Name)'."
        ""
        $Document.Body
    ) -join "`n"
    $Destination = Join-Path $OutputDir "workflow-skills\$($Document.Name)\SKILL.md"
    Write-Utf8 $Destination ($Content.Trim() + "`n")
}

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
Render-Rules "claude" "CLAUDE.md"
Render-Rules "antigravity" "GEMINI.md"
Render-Rules "codex" "AGENTS.md"

Get-ChildItem (Join-Path $RepoRoot "agents") -Filter "*.md" -File |
    Sort-Object Name |
    ForEach-Object { Render-CodexAgent $_.FullName }

Get-ChildItem (Join-Path $RepoRoot "workflows") -Filter "*.md" -File |
    Sort-Object Name |
    ForEach-Object { Render-WorkflowSkill $_.FullName }

if ($SyncSnapshots) {
    Copy-Item (Join-Path $OutputDir "claude\CLAUDE.md") (Join-Path $RepoRoot "claude\CLAUDE.md") -Force
    Copy-Item (Join-Path $OutputDir "antigravity\GEMINI.md") (Join-Path $RepoRoot "gemini\GEMINI.md") -Force
    Write-Host "Synchronized claude/CLAUDE.md and gemini/GEMINI.md snapshots."
}

$AgentCount = @(Get-ChildItem (Join-Path $OutputDir "codex\agents") -Filter "*.toml" -File).Count
$WorkflowSkillCount = @(Get-ChildItem (Join-Path $OutputDir "workflow-skills") -Directory).Count
Write-Host "Built adapters: Codex agents=$AgentCount, workflow skills=$WorkflowSkillCount"
